<?php
/**
 * @file
 * Code for the Ticket feature.
 */

include_once 'ticket.features.inc';
include_once 'TicketController.php';

/**
 * Implements hook_form_alter().
 */
function ticket_form_alter(&$form, &$form_state, $form_id)
{
    if ($form_id != 'ticket_node_form') {
        return;
    }
    $form['field_ticket_atualizacao']['#access'] = false;
    $form['field_ticket_atendido_user']['#access'] = false;
    $form['field_ticket_status']['#access'] = false;
}

/**
 * Implements hook_node_validate().
 */
function ticket_node_validate($node, $form, &$form_state)
{
    $ticketController = new TicketController();
   // kpr($node); die();
}

