<?php
/**
 * @file
 * Code for the Ticket feature.
 */

include_once 'ticket.features.inc';
include_once 'TicketController.php';

/**
 * Implements hook_form_alter().
 */
function ticket_form_alter(&$form, &$form_state, $form_id)
{
    if ($form_id != 'ticket_node_form') {
        return;
    }
    $form['field_ticket_atualizacao']['#access'] = false;
    $form['field_ticket_atendido_user']['#access'] = false;
    $form['field_ticket_status']['#access'] = false;
}

/**
 * Implements hook_views_query_alter().
 */
function ticket_views_query_alter(&$view, &$query)
{
    if ($view->name != 'tickets') {
        return;
    }

    global $user;
    if (in_array('administrador', $user->roles) || in_array('atendente', $user->roles)) {
        return;
    }

    $query->where[1]['conditions'][] = array(
        'field' => 'node.uid',
        'operator' => 'in',
        'value' => array($user->uid)
    );
}